# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/191Jg22bJFB8CqMsw2cLsFR1Cc4jl5Be5
"""

# read scored data
import pandas as pd
data = pd.read_csv("https://trello-attachments.s3.amazonaws.com/5d404847c84f418860597cb6/5d85a3f300231d07d1d5adaa/000de7f0d5836b551b259e2ae195676f/HousingDatasetPrepared_scored.csv")

Y = data["price"]
independent_variables = data.columns
independent_variables = independent_variables.delete(0)
independent_variables = independent_variables.delete(11)
independent_variables

from statsmodels.stats.outliers_influence import variance_inflation_factor as vif
X = data[independent_variables]

for i in range(len(independent_variables)):
  vif_list = [vif(X[independent_variables].values, index) for index in range(len(independent_variables))]
  item = max(vif_list)
  item_index = vif_list.index(item)
  if item > 10:
    independent_variables = independent_variables.delete(item_index)
#print(independent_variables)

# Select Independent variables
# X = data[independent_variables]
X = X[independent_variables]
X.columns

# Model Fitting and Prediction
import statsmodels.api as sm
regression_model = sm.OLS(Y, X)
regression_model = regression_model.fit()

import sys
index_counter = 1
user_dict = {}
for column in X.columns:
  #temp_val = int(input("Enter "+column+": "))
  temp_val = int(sys.argv[index_counter])
  index_counter = index_counter + 1
  user_dict[column] = temp_val
user_input = pd.DataFrame(data=user_dict, index=[0])  
price = regression_model.predict(user_input)
print(round(price[0]))